### PR TITLE
added gdkpd a command as alias of gdkpd auction

### PR DESCRIPTION
**Pull request by linkwodin**
added support to bidders with different language client

### CODE REVIEW

**Comment by Gogo1951** [comment]
Hey @linkwodin can you please update this to fix conflicts? Thanks!

**Comment by linkwodin** [comment]
@Gogo1951

**Comment by Gogo1951** [comment]
Hey @linkwodin ,

Can you re-do this, using the latest as the base? I don't want to re-add all these changes again. Look at all the stuff you're committing here -- it's a lot more than just code for what you intended to do. Let's start with a new PR that just has the stuff you need in it. Thanks!

**Comment by linkwodin** [comment]
it is because, for the traditional Chinese version, we don't have the Fonts\\FRIZQT__.TTF, which will cause the plugin cannot to turn on.

**Comment by Gogo1951** [comment]
Ok, thanks for the explanation.

**Comment by Gogo1951** [comment]
Merging this into Alpha. I don't know how to test this really without Chinese installed. I'll have to rely on bug reports, and it not breaking anything on the English client.

**Comment by KaylinFinke** [comment]
I'm reverting the portion of this change that updated font size as it totally breaks the UI in English. I realize you probably need different sizes for the UI for different fonts, but that must come as part of a change that doesn't break the UI people have been using in the past.

**Pull request merged**
