### PR TITLE
Feature - Export to CSV

### PR DESCRIPTION
**Pull request by xpwn3rx**
Added Export to CSV function for GDPK exporting to ledger spreadsheets.

### CODE REVIEW

**Comment by Gogo1951** [comment]
Hey @xpwn3rx ,

You willing to fix any bugs with this that come up?

I'll merge it into Alpha and let it sit for a week if you're able to hop on any issues people report. Cool?

**Comment by xpwn3rx** [comment]
Sounds good, the code is super basic, like 10 lines. Definitely not rocket science.

**Comment by Gogo1951** [comment]
@xpwn3rx Merged, but would suggest not having 3 separate TOC files. Just adds clutter. My read is that this isn't used for Retail, so we only have to support Classic Era and Wrath. Better to just have the one TOC file with different Interface IDs included.

**Comment by Gogo1951** [comment]
Hey @xpwn3rx ,

So the changes to the ToC files broke the GitHub builder action. Going to back out your changes, and you can re-submit without the ToC changes.

**Comment by xpwn3rx** [comment]
I'm not sure where that came from. I just downloaded the version off the web and installed it then edited and cloned. Let me try downloading the WOTLK version and then making the same changes.

**Comment by Gogo1951** [comment]
Right... it's the Packager that adds that after the fact. Download from GitHub... the version from CurseForge is already "built" and if we add the files manually we break the auto-builder. That make sense?

You can read up on it here. https://github.com/BigWigsMods/packager

We should add this one too... https://github.com/marketplace/actions/toc-interface-updater

**Comment by Gogo1951** [comment]
Add me on GitHub, we can talk through any of this. Gogo#0298

**Pull request merged**
