### PR TITLE
Interpret decimals of form x.y as xy00 bids

### PR DESCRIPTION
**Pull request by samcgardner**

### CODE REVIEW

**Comment by Gogo1951** [comment]
Nice! I'll test this out next time I'm in a raid, probably Tuesday. Thanks mate!

**Comment by Gogo1951** [comment]
Worked when I tested it, but a little shy about merging it without knowing someone else will fix bugs if people find them... @samcgardner you around to fix this if anyone has issues?

**Comment by samcgardner** [comment]
@Gogo1951 sure thing

**Comment by KaylinFinke** [comment]
This appears to only have modified the single auction codepath. Is that intended?

**Comment by Gogo1951** [comment]
Yeah, I think this needs more testing / work. I had some bugs with it last night when I ran it. Was going to try and fix them but I think we'll delay this PR for now and release the other for the time being. 

I don't want to have to wait another week to test... clearly we can do some light testing, but there's no substitute for using it in a real raid to uncover issues.

**Comment by Gogo1951** [comment]
Focusing efforts on rebuild.

**Pull request closed without merging**
